# __          __     _____  _____             ______     __
# \ \        / /\   |  __ \|  __ \           |  _ \ \   / /
#  \ \  /\  / /  \  | |__) | |__) |  ______  | |_) \ \_/ / 
#   \ \/  \/ / /\ \ |  _  /|  ___/  |______| |  _ < \   /  
#    \  /\  / ____ \| | \ \| |               | |_) | | |   
#     \/  \/_/   _\_\_|__\_\_|_  ____        |____/  |_|   
#     /\    \ \ / /  ____| \ | |/ __ \                     
#    /  \    \ V /| |__  |  \| | |  | |                    
#   / /\ \    > < |  __| | . ` | |  | |                    
#  / ____ \  / . \| |____| |\  | |__| |                    
# /_/    \_\/_/ \_\______|_| \_|\____/     

# Changes the language of command feedback/messages.
# fr (Français), en (English)
language: fr